local path = require("doit.core.utils.path")

describe("core utils path", function()
    describe("join", function()
        it("should join path components", function()
            local result = path.join("foo", "bar", "baz")
            assert.are.equal("foo/bar/baz", result)
        end)

        it("should handle single component", function()
            local result = path.join("foo")
            assert.are.equal("foo", result)
        end)
    end)

    describe("dirname", function()
        it("should return directory part of a path", function()
            local result = path.dirname("/home/user/file.txt")
            assert.are.equal("/home/user", result)
        end)

        it("should handle path with no directory", function()
            local result = path.dirname("file.txt")
            assert.are.equal("file.txt", result)
        end)

        it("should handle nested directories", function()
            local result = path.dirname("/a/b/c/d.lua")
            assert.are.equal("/a/b/c", result)
        end)
    end)

    describe("basename", function()
        it("should return filename from path", function()
            local result = path.basename("/home/user/file.txt")
            assert.are.equal("file.txt", result)
        end)

        it("should handle path with no directory", function()
            local result = path.basename("file.txt")
            assert.are.equal("file.txt", result)
        end)
    end)

    describe("exists", function()
        it("should return true for existing file", function()
            -- CLAUDE.md always exists in the repo root
            assert.is_true(path.exists("CLAUDE.md"))
        end)

        it("should return false for non-existent file", function()
            assert.is_false(path.exists("/tmp/doit_nonexistent_file_12345"))
        end)
    end)

    describe("is_dir", function()
        it("should return true for existing directory", function()
            assert.is_true(path.is_dir("lua"))
        end)

        it("should return false for a file", function()
            assert.is_false(path.is_dir("CLAUDE.md"))
        end)

        it("should return false for non-existent path", function()
            assert.is_false(path.is_dir("/tmp/doit_nonexistent_dir_12345"))
        end)
    end)

    describe("ensure_dir", function()
        it("should return true for existing directory", function()
            assert.is_true(path.ensure_dir("lua"))
        end)

        it("should create and return true for new directory", function()
            local test_dir = "/tmp/doit_test_ensure_dir_" .. os.time()
            local result = path.ensure_dir(test_dir)
            assert.is_true(result)
            assert.is_true(path.is_dir(test_dir))
            os.execute("rm -rf " .. test_dir)
        end)
    end)

    describe("get_home", function()
        it("should return a non-empty string", function()
            local home = path.get_home()
            assert.is_string(home)
            assert.is_true(#home > 0)
        end)
    end)

    describe("expand", function()
        it("should expand tilde", function()
            local result = path.expand("~")
            assert.is_string(result)
            assert.is_true(#result > 1)
            assert.falsy(result:match("~"))
        end)
    end)

    describe("get_data_dir", function()
        it("should return a string path", function()
            local data_dir = path.get_data_dir()
            assert.is_string(data_dir)
            assert.is_true(#data_dir > 0)
        end)
    end)
end)
