version: '3'

services:
  dooing-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/plugin
    command: nvim --headless -c "lua require('plenary.test_harness').test_directory('tests')" -c "qa!"

  dooing-interactive:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/plugin
    tty: true
    stdin_open: true
    command: nvim
