name: Run Docker Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Tests
        run: |
          ./docker/run-tests.sh
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "::error::Tests failed with exit code $exit_code"
            exit $exit_code
          fi
